spring:
  cloud:
    gcp:
      project-id: event-subscribers-308123
      credentials:
        encoded-key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZXZlbnQtc3Vic2NyaWJlcnMtMzA4MTIzIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiNjNjMDE2MTBlZGNlODFmNWY5OGQ0YzI0NjZiODY0OTEzYWQ0YWU0NyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDaUJpQlQxc21ZNVlCclxuSmgvam45bC9YUE9pSFZIVS9ZYWIwSy9GR2EzRWdWMXh5VU9EeVVrSGtqRU9TYnJzS3UzR2Z6Q2dWdEV0VHo0SFxuSTBUd0x1dGszNUJrbU8waEc4TTRPdmJRVnF4ZjRGSTcxdDU3Vkt4OGt1cmZ4M3p6UGwvUDZwdFlvZFd2ZlRYN1xucmp1K1FKMmExUU96WU5VRVNNNGwyZUZiclZydGdVSkV3MVM1T3pUNGhCcE9lQTBIUWVnb0Q4VWtNazV1R2x3RVxuY0lwOUNmbUJuZXh6Y3ZhbGcwRVNhaWJ1TTZacHBMRUNzbWk2Uk9ETE5vTVBSY2Z4RGFZYmhiRHdJSUN3SVRDMFxud0ZkLzNUUnZ4eEw3b0ZKa0huMHF0Ym1xdG1PNDM1NU9nOUtlOU9ib1d6TXV4VHRxazQ2SElCclpuUHNTcnNkbVxucW9ZRVVmRUhBZ01CQUFFQ2dnRUFPcFcrZ0xJc2FQV3JMcE0xZXFmbERCRi9Jc0k1UWF0K1RiN3luM0Urak13K1xuRHBPNHJ1Rk1YOGx6cFhmeGQ4MjU5a2t0T3Z6SlcvbklNdXFFMWRnUlU0TW5BY2p1RFVldG1ocHYvanNvenU0Y1xucmZodXIrZVpDdDVRd1NPdndZQnZRbzNSS0FZMGJ1VDJiUSsrR0hmaXhRWjY5UlJ4VWNCRmtoZ3JUV3ZzY2UzMFxueXVIS3U4Y3ViQW9sQVF1akpGUmt5M29rQnhjK3o4Z1pDT2xGeVBDWWJoUElZZ1ZFcTNyVGU5azF2Si85U1NZeFxuNkFib0hxelVxd0wwRUd6N1ZwR2lBcnJvemVaNDhhQ1JCZmp3UVNUV0ZNWlo3TTEyQXBHaE5WcVpTS0JUTlRCSVxuWHF1WHFQVG5KT1JWQ2NOY2IyTEdhYlJNek9UZGtqcU02d29XQ0J1MTRRS0JnUURQVGlvc1lWT2tHdU9KZ1RoY1xuQkdXdkFnZVcvWVAwcDF5QzVJVHltY3hpeGZpaEpsQ3hXSWNwSkhTUURzYm5NZlpQTFdzczNaVUN2MDFvaHZlZ1xueXByZTlNa1R2UFU3VFpJaXV1cnJQWWd3a3JEMlJXMnlNbld3R2JNeml4dmxJRDJGbVU0QjBsUWhzeVZjSnNhRFxuWEt2QjJZYXJVYkV0WU9xVm5kTGhxN1U5VndLQmdRRElGUkUvbmloaHppUHJaT1VvNmlYYkF4czdQZTBnMkF5UFxucWUvU0VoUVozL1BUejVMZjBjMk41d1FxeWp0dWxQNG12TzRnN3o5R00xTCtqeW9ycGl4VjgvYVpYZW5xQzBsRlxuU0IrenhrSU5wUU9MZ1pVc1dqMVM1OW93Y1NZd3pFRjFDQUZYZEJkRW1ZVzM4R0xSWStWQWpxeGVNMlFNR2tZWlxuZ1BLdVp0VHIwUUtCZ1FDWDgrMkoxbFZleHE3ZVRhK29FemtOak9sUFRjaDVmbXViTGpJZE9Zck5JOXZaRTZLMlxuTy9QbXZtZ0thQ3Azc1BHZ20rUWhZTkltejE3SUxaWTVjQWtSUUZCYmZYZ3IzZkl1THVDZlNkMFg3WTUxRmZNUVxuV1ZoV21wLzJPaE5hWWNWMnRpYXR3eVFVQjZKczU2Yy9CcUNIV1JFVFpxLytXVG5hTFhNMEk0Nlh4UUtCZ0QxblxuZ2NpbGNEMDc5M2dabWQ2cHBYNkdnSWY0NUZwdEU4WFBZSU4yK3VaSi9kbW1YYXdGQm5HalVYc1VYNUw3ZE5oTVxucVVSQVNJbngzR20xWkRyTEg5WXRMaVE1VnoxMXcwSFk5YW5Ga2FZQVc0c245TEVNN0w4UjJydDlManhSbzFFWVxuYU5qL0R0a0Z5S3ovd0VRRXhXbS9uNVMxYnVIcitsRi9hbnN0b2ZEUkFvR0JBSXhrL2dyejJpUmxvWENVejk1Q1xuNFZ4NjlDOHFnMWZSUng0MVo2dEJ1OVYyN0hraDlCRnFQRnZWZGhCU3lNWmNIS3owSEtQeHp4S24ybmg5Z214WFxuM3ZTbXhsUm0yRVJmdk9OMVQ5bXFpUXIvWW0yMTJ1MG44NjVjbVhNZ3JCellRMnhQUEgrMFVObHpXUlFHQU54Nlxud3pPcThUeVNMN2NpVFRzK0dVREpJb0FYXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAicHJ1ZWJhc0BldmVudC1zdWJzY3JpYmVycy0zMDgxMjMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA2ODk4MTExNjIxNzY1ODU2NTc4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9wcnVlYmFzJTQwZXZlbnQtc3Vic2NyaWJlcnMtMzA4MTIzLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/friendstore?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Bogota
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming: 
        implicit-strategy: co.com.ingeniods.config.CustomPresistenceNamingStrategy
        physical-strategy: co.com.ingeniods.config.CustomPresistenceNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format-sql: true
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: production

events:
  integration:
    dlq: events-dlq
    events: events-core-sub
    notify: events-store
    executors: 10
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
    root: INFO